# -*- coding: utf-8 -*-
"""Preprocess-data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TN2F13yk268FVM3Jp1fwQq8qlnQlAU_3
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

data = pd.read_csv('/content/Dataset .csv')

data.head()

data.tail()

data.shape

data.describe()

data.info()

data.isnull().sum()

data.dropna(inplace=True)

data_encoded = pd.get_dummies(data, columns=['Cuisines', 'Has Table booking', 'Has Online delivery', 'Price range'])

user_preferences = {'cuisine': 'Japanese', 'price_range': '$$'}

recommended_restaurants = data[data['Cuisines'].str.contains(user_preferences['cuisine']) & (data['Price range'] == user_preferences['price_range'])].head(5)
print("Recommended Restaurants:")
print(recommended_restaurants[['Restaurant Name', 'Cuisines', 'Price range']])

data.dropna(inplace=True)

data_encoded = pd.get_dummies(data, columns=['Cuisines'])


user_cuisine = input("Enter your preferred cuisine: ")
user_price_range = int(input("Enter your preferred price range (1 to 4): "))


recommended_restaurants = data[(data['Cuisines'].str.contains(user_cuisine)) & (data['Price range'] == user_price_range)]

if recommended_restaurants.empty:
    print("No restaurants found matching your preferences.")
else:

    print("Recommended Restaurants:")
    print(recommended_restaurants[['Restaurant Name', 'Cuisines', 'Price range']].head(5))